/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransacoesRouteImport } from './routes/_app.transacoes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNovaTransacaoRouteImport } from './routes/_app.nova-transacao'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaTransacaoRoute = AppNovaTransacaoRouteImport.update({
  id: '/nova-transacao',
  path: '/nova-transacao',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/metas': typeof AppMetasRoute
  '/nova-transacao': typeof AppNovaTransacaoRoute
  '/perfil': typeof AppPerfilRoute
  '/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/metas': typeof AppMetasRoute
  '/nova-transacao': typeof AppNovaTransacaoRoute
  '/perfil': typeof AppPerfilRoute
  '/transacoes': typeof AppTransacoesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/nova-transacao': typeof AppNovaTransacaoRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/transacoes': typeof AppTransacoesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/categorias'
    | '/dashboard'
    | '/metas'
    | '/nova-transacao'
    | '/perfil'
    | '/transacoes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/categorias'
    | '/dashboard'
    | '/metas'
    | '/nova-transacao'
    | '/perfil'
    | '/transacoes'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/cadastro'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/_app/categorias'
    | '/_app/dashboard'
    | '/_app/metas'
    | '/_app/nova-transacao'
    | '/_app/perfil'
    | '/_app/transacoes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transacoes': {
      id: '/_app/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-transacao': {
      id: '/_app/nova-transacao'
      path: '/nova-transacao'
      fullPath: '/nova-transacao'
      preLoaderRoute: typeof AppNovaTransacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMetasRoute: typeof AppMetasRoute
  AppNovaTransacaoRoute: typeof AppNovaTransacaoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMetasRoute: AppMetasRoute,
  AppNovaTransacaoRoute: AppNovaTransacaoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTransacoesRoute: AppTransacoesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
