/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ShareIntentRouteImport } from './routes/share-intent'
import { Route as RedefinirSenhaRouteImport } from './routes/redefinir-senha'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BoasVindasRouteImport } from './routes/boas-vindas'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransacoesRouteImport } from './routes/_app.transacoes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNovaTransacaoRouteImport } from './routes/_app/nova-transacao'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppMaisRouteImport } from './routes/_app.mais'
import { Route as AppFaturasCartaoRouteImport } from './routes/_app.faturas-cartao'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppAssinarRouteImport } from './routes/_app.assinar'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppCartoesIndexRouteImport } from './routes/_app/cartoes/index'
import { Route as AppCartoesNovoRouteImport } from './routes/_app/cartoes/novo'
import { Route as AppCartoesNovaDespesaRouteImport } from './routes/_app/cartoes/nova-despesa'
import { Route as AppCartoesEditarDespesaRouteImport } from './routes/_app/cartoes/editar-despesa'
import { Route as AppCartoesCardIdRouteImport } from './routes/_app/cartoes/$cardId'
import { Route as AppCartoesCardIdFaturaInvoiceIdRouteImport } from './routes/_app/cartoes/$cardId.fatura.$invoiceId'

const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareIntentRoute = ShareIntentRouteImport.update({
  id: '/share-intent',
  path: '/share-intent',
  getParentRoute: () => rootRouteImport,
} as any)
const RedefinirSenhaRoute = RedefinirSenhaRouteImport.update({
  id: '/redefinir-senha',
  path: '/redefinir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BoasVindasRoute = BoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaTransacaoRoute = AppNovaTransacaoRouteImport.update({
  id: '/nova-transacao',
  path: '/nova-transacao',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppMaisRoute = AppMaisRouteImport.update({
  id: '/mais',
  path: '/mais',
  getParentRoute: () => AppRoute,
} as any)
const AppFaturasCartaoRoute = AppFaturasCartaoRouteImport.update({
  id: '/faturas-cartao',
  path: '/faturas-cartao',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppAssinarRoute = AppAssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesIndexRoute = AppCartoesIndexRouteImport.update({
  id: '/cartoes/',
  path: '/cartoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesNovoRoute = AppCartoesNovoRouteImport.update({
  id: '/cartoes/novo',
  path: '/cartoes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesNovaDespesaRoute = AppCartoesNovaDespesaRouteImport.update({
  id: '/cartoes/nova-despesa',
  path: '/cartoes/nova-despesa',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesEditarDespesaRoute = AppCartoesEditarDespesaRouteImport.update({
  id: '/cartoes/editar-despesa',
  path: '/cartoes/editar-despesa',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesCardIdRoute = AppCartoesCardIdRouteImport.update({
  id: '/cartoes/$cardId',
  path: '/cartoes/$cardId',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesCardIdFaturaInvoiceIdRoute =
  AppCartoesCardIdFaturaInvoiceIdRouteImport.update({
    id: '/fatura/$invoiceId',
    path: '/fatura/$invoiceId',
    getParentRoute: () => AppCartoesCardIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/share-intent': typeof ShareIntentRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AppAdminRoute
  '/assinar': typeof AppAssinarRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/faturas-cartao': typeof AppFaturasCartaoRoute
  '/mais': typeof AppMaisRoute
  '/metas': typeof AppMetasRoute
  '/nova-transacao': typeof AppNovaTransacaoRoute
  '/perfil': typeof AppPerfilRoute
  '/transacoes': typeof AppTransacoesRoute
  '/cartoes/$cardId': typeof AppCartoesCardIdRouteWithChildren
  '/cartoes/editar-despesa': typeof AppCartoesEditarDespesaRoute
  '/cartoes/nova-despesa': typeof AppCartoesNovaDespesaRoute
  '/cartoes/novo': typeof AppCartoesNovoRoute
  '/cartoes/': typeof AppCartoesIndexRoute
  '/cartoes/$cardId/fatura/$invoiceId': typeof AppCartoesCardIdFaturaInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/share-intent': typeof ShareIntentRoute
  '/termos': typeof TermosRoute
  '/admin': typeof AppAdminRoute
  '/assinar': typeof AppAssinarRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/faturas-cartao': typeof AppFaturasCartaoRoute
  '/mais': typeof AppMaisRoute
  '/metas': typeof AppMetasRoute
  '/nova-transacao': typeof AppNovaTransacaoRoute
  '/perfil': typeof AppPerfilRoute
  '/transacoes': typeof AppTransacoesRoute
  '/cartoes/$cardId': typeof AppCartoesCardIdRouteWithChildren
  '/cartoes/editar-despesa': typeof AppCartoesEditarDespesaRoute
  '/cartoes/nova-despesa': typeof AppCartoesNovaDespesaRoute
  '/cartoes/novo': typeof AppCartoesNovoRoute
  '/cartoes': typeof AppCartoesIndexRoute
  '/cartoes/$cardId/fatura/$invoiceId': typeof AppCartoesCardIdFaturaInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/redefinir-senha': typeof RedefinirSenhaRoute
  '/share-intent': typeof ShareIntentRoute
  '/termos': typeof TermosRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/assinar': typeof AppAssinarRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/faturas-cartao': typeof AppFaturasCartaoRoute
  '/_app/mais': typeof AppMaisRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/nova-transacao': typeof AppNovaTransacaoRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/transacoes': typeof AppTransacoesRoute
  '/_app/cartoes/$cardId': typeof AppCartoesCardIdRouteWithChildren
  '/_app/cartoes/editar-despesa': typeof AppCartoesEditarDespesaRoute
  '/_app/cartoes/nova-despesa': typeof AppCartoesNovaDespesaRoute
  '/_app/cartoes/novo': typeof AppCartoesNovoRoute
  '/_app/cartoes/': typeof AppCartoesIndexRoute
  '/_app/cartoes/$cardId/fatura/$invoiceId': typeof AppCartoesCardIdFaturaInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boas-vindas'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/share-intent'
    | '/termos'
    | '/admin'
    | '/assinar'
    | '/categorias'
    | '/dashboard'
    | '/faturas-cartao'
    | '/mais'
    | '/metas'
    | '/nova-transacao'
    | '/perfil'
    | '/transacoes'
    | '/cartoes/$cardId'
    | '/cartoes/editar-despesa'
    | '/cartoes/nova-despesa'
    | '/cartoes/novo'
    | '/cartoes/'
    | '/cartoes/$cardId/fatura/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boas-vindas'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/share-intent'
    | '/termos'
    | '/admin'
    | '/assinar'
    | '/categorias'
    | '/dashboard'
    | '/faturas-cartao'
    | '/mais'
    | '/metas'
    | '/nova-transacao'
    | '/perfil'
    | '/transacoes'
    | '/cartoes/$cardId'
    | '/cartoes/editar-despesa'
    | '/cartoes/nova-despesa'
    | '/cartoes/novo'
    | '/cartoes'
    | '/cartoes/$cardId/fatura/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/boas-vindas'
    | '/cadastro'
    | '/login'
    | '/privacidade'
    | '/recuperar-senha'
    | '/redefinir-senha'
    | '/share-intent'
    | '/termos'
    | '/_app/admin'
    | '/_app/assinar'
    | '/_app/categorias'
    | '/_app/dashboard'
    | '/_app/faturas-cartao'
    | '/_app/mais'
    | '/_app/metas'
    | '/_app/nova-transacao'
    | '/_app/perfil'
    | '/_app/transacoes'
    | '/_app/cartoes/$cardId'
    | '/_app/cartoes/editar-despesa'
    | '/_app/cartoes/nova-despesa'
    | '/_app/cartoes/novo'
    | '/_app/cartoes/'
    | '/_app/cartoes/$cardId/fatura/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  BoasVindasRoute: typeof BoasVindasRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
  RedefinirSenhaRoute: typeof RedefinirSenhaRoute
  ShareIntentRoute: typeof ShareIntentRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share-intent': {
      id: '/share-intent'
      path: '/share-intent'
      fullPath: '/share-intent'
      preLoaderRoute: typeof ShareIntentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redefinir-senha': {
      id: '/redefinir-senha'
      path: '/redefinir-senha'
      fullPath: '/redefinir-senha'
      preLoaderRoute: typeof RedefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boas-vindas': {
      id: '/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof BoasVindasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transacoes': {
      id: '/_app/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-transacao': {
      id: '/_app/nova-transacao'
      path: '/nova-transacao'
      fullPath: '/nova-transacao'
      preLoaderRoute: typeof AppNovaTransacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/mais': {
      id: '/_app/mais'
      path: '/mais'
      fullPath: '/mais'
      preLoaderRoute: typeof AppMaisRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/faturas-cartao': {
      id: '/_app/faturas-cartao'
      path: '/faturas-cartao'
      fullPath: '/faturas-cartao'
      preLoaderRoute: typeof AppFaturasCartaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assinar': {
      id: '/_app/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AppAssinarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/': {
      id: '/_app/cartoes/'
      path: '/cartoes'
      fullPath: '/cartoes/'
      preLoaderRoute: typeof AppCartoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/novo': {
      id: '/_app/cartoes/novo'
      path: '/cartoes/novo'
      fullPath: '/cartoes/novo'
      preLoaderRoute: typeof AppCartoesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/nova-despesa': {
      id: '/_app/cartoes/nova-despesa'
      path: '/cartoes/nova-despesa'
      fullPath: '/cartoes/nova-despesa'
      preLoaderRoute: typeof AppCartoesNovaDespesaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/editar-despesa': {
      id: '/_app/cartoes/editar-despesa'
      path: '/cartoes/editar-despesa'
      fullPath: '/cartoes/editar-despesa'
      preLoaderRoute: typeof AppCartoesEditarDespesaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/$cardId': {
      id: '/_app/cartoes/$cardId'
      path: '/cartoes/$cardId'
      fullPath: '/cartoes/$cardId'
      preLoaderRoute: typeof AppCartoesCardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/$cardId/fatura/$invoiceId': {
      id: '/_app/cartoes/$cardId/fatura/$invoiceId'
      path: '/fatura/$invoiceId'
      fullPath: '/cartoes/$cardId/fatura/$invoiceId'
      preLoaderRoute: typeof AppCartoesCardIdFaturaInvoiceIdRouteImport
      parentRoute: typeof AppCartoesCardIdRoute
    }
  }
}

interface AppCartoesCardIdRouteChildren {
  AppCartoesCardIdFaturaInvoiceIdRoute: typeof AppCartoesCardIdFaturaInvoiceIdRoute
}

const AppCartoesCardIdRouteChildren: AppCartoesCardIdRouteChildren = {
  AppCartoesCardIdFaturaInvoiceIdRoute: AppCartoesCardIdFaturaInvoiceIdRoute,
}

const AppCartoesCardIdRouteWithChildren =
  AppCartoesCardIdRoute._addFileChildren(AppCartoesCardIdRouteChildren)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppAssinarRoute: typeof AppAssinarRoute
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppFaturasCartaoRoute: typeof AppFaturasCartaoRoute
  AppMaisRoute: typeof AppMaisRoute
  AppMetasRoute: typeof AppMetasRoute
  AppNovaTransacaoRoute: typeof AppNovaTransacaoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppCartoesCardIdRoute: typeof AppCartoesCardIdRouteWithChildren
  AppCartoesEditarDespesaRoute: typeof AppCartoesEditarDespesaRoute
  AppCartoesNovaDespesaRoute: typeof AppCartoesNovaDespesaRoute
  AppCartoesNovoRoute: typeof AppCartoesNovoRoute
  AppCartoesIndexRoute: typeof AppCartoesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppAssinarRoute: AppAssinarRoute,
  AppCategoriasRoute: AppCategoriasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppFaturasCartaoRoute: AppFaturasCartaoRoute,
  AppMaisRoute: AppMaisRoute,
  AppMetasRoute: AppMetasRoute,
  AppNovaTransacaoRoute: AppNovaTransacaoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppCartoesCardIdRoute: AppCartoesCardIdRouteWithChildren,
  AppCartoesEditarDespesaRoute: AppCartoesEditarDespesaRoute,
  AppCartoesNovaDespesaRoute: AppCartoesNovaDespesaRoute,
  AppCartoesNovoRoute: AppCartoesNovoRoute,
  AppCartoesIndexRoute: AppCartoesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  BoasVindasRoute: BoasVindasRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
  RedefinirSenhaRoute: RedefinirSenhaRoute,
  ShareIntentRoute: ShareIntentRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
