/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RecuperarSenhaRouteImport } from './routes/recuperar-senha'
import { Route as PlanosRouteImport } from './routes/planos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BoasVindasRouteImport } from './routes/boas-vindas'
import { Route as AssinaturaSucessoRouteImport } from './routes/assinatura-sucesso'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppTransacoesRouteImport } from './routes/_app.transacoes'
import { Route as AppPerfilRouteImport } from './routes/_app.perfil'
import { Route as AppNovaTransacaoRouteImport } from './routes/_app.nova-transacao'
import { Route as AppMetasRouteImport } from './routes/_app.metas'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppCategoriasRouteImport } from './routes/_app.categorias'
import { Route as AppCartoesIndexRouteImport } from './routes/_app/cartoes/index'
import { Route as AppCartoesNovoRouteImport } from './routes/_app/cartoes/novo'
import { Route as AppCartoesNovaDespesaRouteImport } from './routes/_app/cartoes/nova-despesa'
import { Route as AppCartoesCardIdRouteImport } from './routes/_app/cartoes/$cardId'
import { Route as AppCartoesCardId_faturaInvoiceIdRouteImport } from './routes/_app/cartoes/$cardId_fatura.$invoiceId'
import { Route as AppCartoesCardIdFaturaInvoiceIdRouteImport } from './routes/_app/cartoes/$cardId_.fatura.$invoiceId'

const RecuperarSenhaRoute = RecuperarSenhaRouteImport.update({
  id: '/recuperar-senha',
  path: '/recuperar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanosRoute = PlanosRouteImport.update({
  id: '/planos',
  path: '/planos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BoasVindasRoute = BoasVindasRouteImport.update({
  id: '/boas-vindas',
  path: '/boas-vindas',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaSucessoRoute = AssinaturaSucessoRouteImport.update({
  id: '/assinatura-sucesso',
  path: '/assinatura-sucesso',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTransacoesRoute = AppTransacoesRouteImport.update({
  id: '/transacoes',
  path: '/transacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppPerfilRoute = AppPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AppRoute,
} as any)
const AppNovaTransacaoRoute = AppNovaTransacaoRouteImport.update({
  id: '/nova-transacao',
  path: '/nova-transacao',
  getParentRoute: () => AppRoute,
} as any)
const AppMetasRoute = AppMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppCategoriasRoute = AppCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesIndexRoute = AppCartoesIndexRouteImport.update({
  id: '/cartoes/',
  path: '/cartoes/',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesNovoRoute = AppCartoesNovoRouteImport.update({
  id: '/cartoes/novo',
  path: '/cartoes/novo',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesNovaDespesaRoute = AppCartoesNovaDespesaRouteImport.update({
  id: '/cartoes/nova-despesa',
  path: '/cartoes/nova-despesa',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesCardIdRoute = AppCartoesCardIdRouteImport.update({
  id: '/cartoes/$cardId',
  path: '/cartoes/$cardId',
  getParentRoute: () => AppRoute,
} as any)
const AppCartoesCardId_faturaInvoiceIdRoute =
  AppCartoesCardId_faturaInvoiceIdRouteImport.update({
    id: '/cartoes/$cardId_fatura/$invoiceId',
    path: '/cartoes/$cardId_fatura/$invoiceId',
    getParentRoute: () => AppRoute,
  } as any)
const AppCartoesCardIdFaturaInvoiceIdRoute =
  AppCartoesCardIdFaturaInvoiceIdRouteImport.update({
    id: '/cartoes/$cardId_/fatura/$invoiceId',
    path: '/cartoes/$cardId/fatura/$invoiceId',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assinatura-sucesso': typeof AssinaturaSucessoRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/metas': typeof AppMetasRoute
  '/nova-transacao': typeof AppNovaTransacaoRoute
  '/perfil': typeof AppPerfilRoute
  '/transacoes': typeof AppTransacoesRoute
  '/cartoes/$cardId': typeof AppCartoesCardIdRoute
  '/cartoes/nova-despesa': typeof AppCartoesNovaDespesaRoute
  '/cartoes/novo': typeof AppCartoesNovoRoute
  '/cartoes/': typeof AppCartoesIndexRoute
  '/cartoes/$cardId_fatura/$invoiceId': typeof AppCartoesCardId_faturaInvoiceIdRoute
  '/cartoes/$cardId/fatura/$invoiceId': typeof AppCartoesCardIdFaturaInvoiceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/assinatura-sucesso': typeof AssinaturaSucessoRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/categorias': typeof AppCategoriasRoute
  '/dashboard': typeof AppDashboardRoute
  '/metas': typeof AppMetasRoute
  '/nova-transacao': typeof AppNovaTransacaoRoute
  '/perfil': typeof AppPerfilRoute
  '/transacoes': typeof AppTransacoesRoute
  '/cartoes/$cardId': typeof AppCartoesCardIdRoute
  '/cartoes/nova-despesa': typeof AppCartoesNovaDespesaRoute
  '/cartoes/novo': typeof AppCartoesNovoRoute
  '/cartoes': typeof AppCartoesIndexRoute
  '/cartoes/$cardId_fatura/$invoiceId': typeof AppCartoesCardId_faturaInvoiceIdRoute
  '/cartoes/$cardId/fatura/$invoiceId': typeof AppCartoesCardIdFaturaInvoiceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRoute
  '/assinatura-sucesso': typeof AssinaturaSucessoRoute
  '/boas-vindas': typeof BoasVindasRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/planos': typeof PlanosRoute
  '/recuperar-senha': typeof RecuperarSenhaRoute
  '/_app/categorias': typeof AppCategoriasRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/metas': typeof AppMetasRoute
  '/_app/nova-transacao': typeof AppNovaTransacaoRoute
  '/_app/perfil': typeof AppPerfilRoute
  '/_app/transacoes': typeof AppTransacoesRoute
  '/_app/cartoes/$cardId': typeof AppCartoesCardIdRoute
  '/_app/cartoes/nova-despesa': typeof AppCartoesNovaDespesaRoute
  '/_app/cartoes/novo': typeof AppCartoesNovoRoute
  '/_app/cartoes/': typeof AppCartoesIndexRoute
  '/_app/cartoes/$cardId_fatura/$invoiceId': typeof AppCartoesCardId_faturaInvoiceIdRoute
  '/_app/cartoes/$cardId_/fatura/$invoiceId': typeof AppCartoesCardIdFaturaInvoiceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/assinatura-sucesso'
    | '/boas-vindas'
    | '/cadastro'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/categorias'
    | '/dashboard'
    | '/metas'
    | '/nova-transacao'
    | '/perfil'
    | '/transacoes'
    | '/cartoes/$cardId'
    | '/cartoes/nova-despesa'
    | '/cartoes/novo'
    | '/cartoes/'
    | '/cartoes/$cardId_fatura/$invoiceId'
    | '/cartoes/$cardId/fatura/$invoiceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/assinatura-sucesso'
    | '/boas-vindas'
    | '/cadastro'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/categorias'
    | '/dashboard'
    | '/metas'
    | '/nova-transacao'
    | '/perfil'
    | '/transacoes'
    | '/cartoes/$cardId'
    | '/cartoes/nova-despesa'
    | '/cartoes/novo'
    | '/cartoes'
    | '/cartoes/$cardId_fatura/$invoiceId'
    | '/cartoes/$cardId/fatura/$invoiceId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/admin'
    | '/assinatura-sucesso'
    | '/boas-vindas'
    | '/cadastro'
    | '/login'
    | '/planos'
    | '/recuperar-senha'
    | '/_app/categorias'
    | '/_app/dashboard'
    | '/_app/metas'
    | '/_app/nova-transacao'
    | '/_app/perfil'
    | '/_app/transacoes'
    | '/_app/cartoes/$cardId'
    | '/_app/cartoes/nova-despesa'
    | '/_app/cartoes/novo'
    | '/_app/cartoes/'
    | '/_app/cartoes/$cardId_fatura/$invoiceId'
    | '/_app/cartoes/$cardId_/fatura/$invoiceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRoute
  AssinaturaSucessoRoute: typeof AssinaturaSucessoRoute
  BoasVindasRoute: typeof BoasVindasRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PlanosRoute: typeof PlanosRoute
  RecuperarSenhaRoute: typeof RecuperarSenhaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recuperar-senha': {
      id: '/recuperar-senha'
      path: '/recuperar-senha'
      fullPath: '/recuperar-senha'
      preLoaderRoute: typeof RecuperarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planos': {
      id: '/planos'
      path: '/planos'
      fullPath: '/planos'
      preLoaderRoute: typeof PlanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boas-vindas': {
      id: '/boas-vindas'
      path: '/boas-vindas'
      fullPath: '/boas-vindas'
      preLoaderRoute: typeof BoasVindasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura-sucesso': {
      id: '/assinatura-sucesso'
      path: '/assinatura-sucesso'
      fullPath: '/assinatura-sucesso'
      preLoaderRoute: typeof AssinaturaSucessoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/transacoes': {
      id: '/_app/transacoes'
      path: '/transacoes'
      fullPath: '/transacoes'
      preLoaderRoute: typeof AppTransacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/perfil': {
      id: '/_app/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AppPerfilRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/nova-transacao': {
      id: '/_app/nova-transacao'
      path: '/nova-transacao'
      fullPath: '/nova-transacao'
      preLoaderRoute: typeof AppNovaTransacaoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/metas': {
      id: '/_app/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AppMetasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/categorias': {
      id: '/_app/categorias'
      path: '/categorias'
      fullPath: '/categorias'
      preLoaderRoute: typeof AppCategoriasRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/': {
      id: '/_app/cartoes/'
      path: '/cartoes'
      fullPath: '/cartoes/'
      preLoaderRoute: typeof AppCartoesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/novo': {
      id: '/_app/cartoes/novo'
      path: '/cartoes/novo'
      fullPath: '/cartoes/novo'
      preLoaderRoute: typeof AppCartoesNovoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/nova-despesa': {
      id: '/_app/cartoes/nova-despesa'
      path: '/cartoes/nova-despesa'
      fullPath: '/cartoes/nova-despesa'
      preLoaderRoute: typeof AppCartoesNovaDespesaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/$cardId': {
      id: '/_app/cartoes/$cardId'
      path: '/cartoes/$cardId'
      fullPath: '/cartoes/$cardId'
      preLoaderRoute: typeof AppCartoesCardIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/$cardId_fatura/$invoiceId': {
      id: '/_app/cartoes/$cardId_fatura/$invoiceId'
      path: '/cartoes/$cardId_fatura/$invoiceId'
      fullPath: '/cartoes/$cardId_fatura/$invoiceId'
      preLoaderRoute: typeof AppCartoesCardId_faturaInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cartoes/$cardId_/fatura/$invoiceId': {
      id: '/_app/cartoes/$cardId_/fatura/$invoiceId'
      path: '/cartoes/$cardId/fatura/$invoiceId'
      fullPath: '/cartoes/$cardId/fatura/$invoiceId'
      preLoaderRoute: typeof AppCartoesCardIdFaturaInvoiceIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCategoriasRoute: typeof AppCategoriasRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppMetasRoute: typeof AppMetasRoute
  AppNovaTransacaoRoute: typeof AppNovaTransacaoRoute
  AppPerfilRoute: typeof AppPerfilRoute
  AppTransacoesRoute: typeof AppTransacoesRoute
  AppCartoesCardIdRoute: typeof AppCartoesCardIdRoute
  AppCartoesNovaDespesaRoute: typeof AppCartoesNovaDespesaRoute
  AppCartoesNovoRoute: typeof AppCartoesNovoRoute
  AppCartoesIndexRoute: typeof AppCartoesIndexRoute
  AppCartoesCardId_faturaInvoiceIdRoute: typeof AppCartoesCardId_faturaInvoiceIdRoute
  AppCartoesCardIdFaturaInvoiceIdRoute: typeof AppCartoesCardIdFaturaInvoiceIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCategoriasRoute: AppCategoriasRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppMetasRoute: AppMetasRoute,
  AppNovaTransacaoRoute: AppNovaTransacaoRoute,
  AppPerfilRoute: AppPerfilRoute,
  AppTransacoesRoute: AppTransacoesRoute,
  AppCartoesCardIdRoute: AppCartoesCardIdRoute,
  AppCartoesNovaDespesaRoute: AppCartoesNovaDespesaRoute,
  AppCartoesNovoRoute: AppCartoesNovoRoute,
  AppCartoesIndexRoute: AppCartoesIndexRoute,
  AppCartoesCardId_faturaInvoiceIdRoute: AppCartoesCardId_faturaInvoiceIdRoute,
  AppCartoesCardIdFaturaInvoiceIdRoute: AppCartoesCardIdFaturaInvoiceIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRoute,
  AssinaturaSucessoRoute: AssinaturaSucessoRoute,
  BoasVindasRoute: BoasVindasRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PlanosRoute: PlanosRoute,
  RecuperarSenhaRoute: RecuperarSenhaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
